# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bayesian Bradley-Terry model for single game
#' 
#' Calculates Glicko ratings based on Bayesian Bradley Terry model.
#' 
#' Algorithm based on 'A Bayesian Approximation Method for Online Ranking' by Ruby C. Weng and Chih-Jen Lin
#' @param rank.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param kappa
#' @param gamma
#' @return \code{r} updated ratings of participats
#' @return \code{rd} updated deviations of participants ratings
#' @return \code{expected} matrix of expected score. \code{expected[i, j] = P(i > j)} 
#' @export
bbt <- function(team_name, rank, r, rd, sig, weight, kappa = 0.0001, gamma = 1.0, init_r = 25, init_rd = 25/3, beta = 25/6) {
    .Call('_sport_bbt', PACKAGE = 'sport', team_name, rank, r, rd, sig, weight, kappa, gamma, init_r, init_rd, beta)
}

#' Dynamic Bayesian Logit
#' 
#' Calculates ratings using extended Kalman Filter.
#' @param rank.
#' @param R Matrix of coefficients (ratings).
#' @param X Matrix of player specifics.
#' @param RD Matrix of coefficients deviations
#' @return \code{r} updated ratings of participats
#' @return \code{rd} updated deviations of participants ratings
#' @return \code{expected} matrix of expected score. \code{expected[i, j] = P(i > j)} 
#' @export
dbl <- function(team_name, rank, X, R, RD, sig, weight) {
    .Call('_sport_dbl', PACKAGE = 'sport', team_name, rank, X, R, RD, sig, weight)
}

#' FIDE rating for single game
#' 
#' FIDE Rating Regulations effective from 1 July 2014
#' 
#' @param teams name of event participants.
#' @param rank classification of the event.
#' @param days days after previous match - indicator multiplying uncertainty of expectations.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @examples
#'fide(
#'  teams = c( "A", "B", "C", "D", "E", "F" ), 
#'  rank  = c( 3, 2, 3, 5, 6, 1), 
#'  r     = c( 1613, 1609, 1477, 1388, 1586, 1720 ) , 
#'  init_r  = 1500,
#'  init_rd = 100
#')
#' @export
fide <- function(teams, rank, r, K = 32L, init_r = 1500, init_rd = 350) {
    .Call('_sport_fide', PACKAGE = 'sport', teams, rank, r, K, init_r, init_rd)
}

#' Glicko rating for single game
#'
#' Calculates Glicko rating for single game input
#' 
#' @param team_name name of event participants.
#' @param rank classification of the event.
#' @param time time after previous match - indicator multiplying uncertainty of expectations.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param sig 
#' @param weight increase/decrease update of the parameter in particular event. Lower values makes parameter update smaller
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @return \code{r} updated ratings of participats
#' @return \code{rd} updated deviations of participants ratings
#' @return \code{expected} matrix of expected score. \code{expected[i, j] = P(i > j)} 
#' @examples
#'glicko(
#'  team_name = c( "A", "B", "C", "D" ), 
#'  rank  = c( 3, 4, 1, 2 ), 
#'  time  = c( 0, 0, 0, 0),
#'  r     = c( 1500, 1400, 1550, 1700 ) , 
#'  rd    = c( 200,  30,   100,  300 ),
#'  init_r  = 1500,
#'  init_rd = 100
#')
#'glicko(
#' team_name = c( "A", "B" ), 
#'   rank  = c( 1, 2 ), 
#'   time  = c( 0, 0),
#'   r     = c( 1400, 1500 ) , 
#'   rd    = c( 80,  150),
#'   init_r  = 1500,
#'   init_rd = 100
#')
#' @export
glicko <- function(team_name, rank, r, rd, sig, weight, init_r = 1500.00, init_rd = 350.00, gamma = 1) {
    .Call('_sport_glicko', PACKAGE = 'sport', team_name, rank, r, rd, sig, weight, init_r, init_rd, gamma)
}

#' Glicko2 rating for single game
#' 
#' Calculates Glicko2 rating for single game input
#' 
#' @param team_name name of event participants.
#' @param rank classification of the event.
#' @param r ratings of participants.
#' @param rd ratings standard deviations.
#' @param sig rating volatility. The volatility measure indicates the degree of expected fluctuation in a player’s rating. The volatility measure is high when a player has erratic performances (e.g., when the player has had exceptionally strong results after a period of stability), and the volatility measure is low when the player performs at a consistent level
#' @param weight weight influencing variation.
#' @param tau The system constant. Which constrains the change in volatility over time. Reasonable choices are between 0.3 and 1.2 (`default = 0.5`), though the system should be tested to decide which value results in greatest predictive accuracy. Smaller values of `tau` prevent the volatility measures from changing by largeamounts, which in turn prevent enormous changes in ratings based on very improbable results. If the application of Glicko-2 is expected to involve extremely improbable collections of game outcomes, then `tau` should be set to a small value, even as small as, say, `tau= 0`.2.
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @return \code{r} updated ratings of participats
#' @return \code{rd} updated deviations of participants ratings
#' @return \code{expected} matrix of expected score. \code{expected[i, j] = P(i > j)} 
#' @examples
#'glicko2(
#'  team_name = c( "A", "B", "C", "D" ), 
#'  rank  = c( 3, 4, 1, 2 ), 
#'  weight = c( 1, 1, 1, 1),
#'  r     = c( 1500, 1400, 1550, 1700 ) , 
#'  rd    = c( 200,  30,   100,  300 ),
#'  sig   = c( .06, .06, .05, .07),
#'  tau   = .5,
#'  init_r  = 1500,
#'  init_rd = 100
#')
#' @export
glicko2 <- function(team_name, rank, r, rd, sig, weight, tau = .5, init_r = 1500.00, init_rd = 350.00) {
    .Call('_sport_glicko2', PACKAGE = 'sport', team_name, rank, r, rd, sig, weight, tau, init_r, init_rd)
}

#' Harkness rating for single game
#' 
#' Calculates Harkness rating for single game input
#' 
#' @param teams name of event participants.
#' @param rank classification of the event.
#' @param days days after previous match - indicator multiplying uncertainty of expectations.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @examples
#'  teams <- c("A","B","C","D")
#'  rank  <- c(3 , 4 , 1, 2)
#'  days  <- rep(0, 4)
#'  r     <- c(1500, 1400, 1550, 1700) 
#'  rd    <- c(200,  30,   100,  300)
#'  harkness(
#'    teams = teams, 
#'    rank  = rank, 
#'    days  = days,
#'    r     = r, 
#'    rd    = rd,
#'    init_r  = 1500,
#'    init_rd = 100)
#' @export
harkness <- function(teams, rank, days, r, rd, init_r = 1500, init_rd = 350) {
    .Call('_sport_harkness', PACKAGE = 'sport', teams, rank, days, r, rd, init_r, init_rd)
}

#' Dummy matrix from factor
#'
#' Dummy matrix from factor
#' @param factor to be transormed into dummy matrix
#' @export
factor2dummy <- function(factor) {
    .Call('_sport_factor2dummy', PACKAGE = 'sport', factor)
}

