# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' FIDE rating for single game
#' 
#' FIDE Rating Regulations effective from 1 July 2014
#' 
#' @param teams name of event participants.
#' @param rank classification of the event.
#' @param days days after previous match - indicator multiplying uncertainty of expectations.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @examples
#'elo(
#'  teams = c( "A", "B", "C", "D", "E", "F" ), 
#'  rank  = c( 3, 2, 3, 5, 6, 1), 
#'  r     = c( 1613, 1609, 1477, 1388, 1586, 1720 ) , 
#'  init_r  = 1500,
#'  init_rd = 100
#')
#' @export
fide <- function(teams, rank, r, K = 32L, init_r = 1500, init_rd = 350) {
    .Call('sport_fide', PACKAGE = 'sport', teams, rank, r, K, init_r, init_rd)
}

#' Glicko rating for single game
#' 
#' Calculates Glicko rating for single game input
#' 
#' @param teams name of event participants.
#' @param rank classification of the event.
#' @param days days after previous match - indicator multiplying uncertainty of expectations.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @return \code{r} updated ratings of participats
#' @return \code{rd} updated deviations of participants ratings
#' @return \code{expected} matrix of expected score. \code{expected[i, j] = P(i > j)} 
#' @examples
#'glicko(
#'  teams = c( "A", "B", "C", "D" ), 
#'  rank  = c( 3, 4, 1, 2 ), 
#'  days  = c( 0, 0, 0, 0),
#'  r     = c( 1500, 1400, 1550, 1700 ) , 
#'  rd    = c( 200,  30,   100,  300 ),
#'  init_r  = 1500,
#'  init_rd = 100
#')
#' @export
glicko <- function(teams, rank, r, rd, days = as.numeric( c(0)), init_r = 1500.00, init_rd = 350.00) {
    .Call('sport_glicko', PACKAGE = 'sport', teams, rank, r, rd, days, init_r, init_rd)
}

#' Glicko rating for single game
#' 
#' Calculates Glicko rating for single game input
#' 
#' @param teams name of event participants.
#' @param rank classification of the event.
#' @param days days after previous match - indicator multiplying uncertainty of expectations.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @return \code{r} updated ratings of participats
#' @return \code{rd} updated deviations of participants ratings
#' @return \code{expected} matrix of expected score. \code{expected[i, j] = P(i > j)} 
#' @examples
#'glicko2(
#'  teams = c( "A", "B", "C", "D" ), 
#'  rank  = c( 3, 4, 1, 2 ), 
#'  days  = c( 0, 0, 0, 0),
#'  r     = c( 1500, 1400, 1550, 1700 ) , 
#'  rd    = c( 200,  30,   100,  300 ),
#'  sig   = c( .06, .06, .05, .07),
#'  tau   = .5,
#'  init_r  = 1500,
#'  init_rd = 100
#')
#' @export
glicko2 <- function(teams, rank, r, rd, sig, days = as.numeric( c(0)), tau = .5, init_r = 1500.00, init_rd = 350.00) {
    .Call('sport_glicko2', PACKAGE = 'sport', teams, rank, r, rd, sig, days, tau, init_r, init_rd)
}

#' Harkness rating for single game
#' 
#' Calculates Harkness rating for single game input
#' 
#' @param teams name of event participants.
#' @param rank classification of the event.
#' @param days days after previous match - indicator multiplying uncertainty of expectations.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @examples
#'  teams <- c("A","B","C","D")
#'  rank  <- c(3 , 4 , 1, 2)
#'  days  <- rep(0, 4)
#'  r     <- c(1500, 1400, 1550, 1700) 
#'  rd    <- c(200,  30,   100,  300)
#'  harkness(
#'    teams = teams, 
#'    rank  = rank, 
#'    days  = days,
#'    r     = r, 
#'    rd    = rd,
#'    init_r  = 1500,
#'    init_rd = 100)
#' @export
harkness <- function(teams, rank, days, r, rd, init_r = 1500, init_rd = 350) {
    .Call('sport_harkness', PACKAGE = 'sport', teams, rank, days, r, rd, init_r, init_rd)
}

#' Calculate points
#' 
#' Calculates points of \code{event_id} participant with given parameters
#' 
#' @param x A single integer.
#' @export
pointsCalc <- function(event_id, team_name, score) {
    .Call('sport_pointsCalc', PACKAGE = 'sport', event_id, team_name, score)
}

#' @export
rcpp_hello_world <- function() {
    .Call('sport_rcpp_hello_world', PACKAGE = 'sport')
}

#' Streak length of vector elements
#' 
#' Calculates series of consecutive elements
#' 
#' @param x A single integer.
#' @examples
#' x <- c(1,1,0,0,1,0,3,3,1,1)
#' streakLength(x)
#' @export
streakLength <- function(vec) {
    .Call('sport_streakLength', PACKAGE = 'sport', vec)
}

