# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bbt <- function(name, rank, r, rd, sig, weight, identifier, kappa = 0.0001, gamma = 999, beta = 25/6, init_r = 25, init_rd = 25/3) {
    .Call('_sport_bbt', PACKAGE = 'sport', name, rank, r, rd, sig, weight, identifier, kappa, gamma, beta, init_r, init_rd)
}

dbl <- function(name, rank, X, R, RD, sig, weight, identifier) {
    .Call('_sport_dbl', PACKAGE = 'sport', name, rank, X, R, RD, sig, weight, identifier)
}

factor2dummy <- function(factor) {
    .Call('_sport_factor2dummy', PACKAGE = 'sport', factor)
}

glicko <- function(name, rank, r, rd, sig, weight, identifier, init_r = 1500.00, init_rd = 350.00, gamma = 1) {
    .Call('_sport_glicko', PACKAGE = 'sport', name, rank, r, rd, sig, weight, identifier, init_r, init_rd, gamma)
}

glicko2 <- function(name, rank, r, rd, sig, weight, identifier, tau = .5, init_r = 1500.00, init_rd = 350.00) {
    .Call('_sport_glicko2', PACKAGE = 'sport', name, rank, r, rd, sig, weight, identifier, tau, init_r, init_rd)
}

#' Harkness rating for single game
#' 
#' Calculates Harkness rating for single game input
#' 
#' @param teams name of event participants.
#' @param rank classification of the event.
#' @param days days after previous match - indicator multiplying uncertainty of expectations.
#' @param r ratings of participants.
#' @param rd rating deviations of participants.
#' @param init_r initial rating for new competitors (contains NA). Default = 1500
#' @param init_rd initial rating deviations for new competitors. Default = 350
#' @examples
#'  teams <- c("A","B","C","D")
#'  rank  <- c(3 , 4 , 1, 2)
#'  days  <- rep(0, 4)
#'  r     <- c(1500, 1400, 1550, 1700) 
#'  rd    <- c(200,  30,   100,  300)
#'  harkness(
#'    teams = teams, 
#'    rank  = rank, 
#'    days  = days,
#'    r     = r, 
#'    rd    = rd,
#'    init_r  = 1500,
#'    init_rd = 100)
#' @export
harkness <- function(teams, rank, days, r, rd, init_r = 1500, init_rd = 350) {
    .Call('_sport_harkness', PACKAGE = 'sport', teams, rank, days, r, rd, init_r, init_rd)
}

